services:
  ltesniffer:
    image: ltesniffer
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ltesniffer
    privileged: true
    restart: unless-stopped
    network_mode: host
    volumes:
      - "/dev/bus/usb:/dev/bus/usb"
    working_dir: /home
    tty: true
    stdin_open: true
